//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LujetonA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cartera
    {
        public int idcartera { get; set; }
        public Nullable<int> abono { get; set; }
        public Nullable<int> idfactura { get; set; }
    
        public virtual factura factura { get; set; }
    }
}
