//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LujetonA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_factura
    {
        public int id { get; set; }
        public Nullable<int> idFactura { get; set; }
        public Nullable<int> idProducto { get; set; }
        public Nullable<double> precio { get; set; }
        public Nullable<int> cantidad { get; set; }
    
        public virtual factura factura { get; set; }
    }
}
