//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LujetonA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class menu_perfil
    {
        public int id { get; set; }
        public Nullable<int> id_perfil { get; set; }
        public Nullable<int> id_menu { get; set; }
    
        public virtual menu menu { get; set; }
        public virtual perfil perfil { get; set; }
    }
}
