//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LujetonA.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bd_proyectoEntities1 : DbContext
    {
        public bd_proyectoEntities1()
            : base("name=bd_proyectoEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bodega> bodega { get; set; }
        public virtual DbSet<cartera> cartera { get; set; }
        public virtual DbSet<categoria> categoria { get; set; }
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<datos_empresa> datos_empresa { get; set; }
        public virtual DbSet<detalle_factura> detalle_factura { get; set; }
        public virtual DbSet<empleado> empleado { get; set; }
        public virtual DbSet<entrada> entrada { get; set; }
        public virtual DbSet<factura> factura { get; set; }
        public virtual DbSet<menu> menu { get; set; }
        public virtual DbSet<menu_perfil> menu_perfil { get; set; }
        public virtual DbSet<movimiento> movimiento { get; set; }
        public virtual DbSet<perfil> perfil { get; set; }
        public virtual DbSet<producto> producto { get; set; }
        public virtual DbSet<producto_bodega> producto_bodega { get; set; }
        public virtual DbSet<proveedor> proveedor { get; set; }
        public virtual DbSet<tipomovimiento> tipomovimiento { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
        public virtual DbSet<v_producto_real_stock> v_producto_real_stock { get; set; }
    }
}
