//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LujetonA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class movimiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public movimiento()
        {
            this.producto_bodega = new HashSet<producto_bodega>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> idProducto { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<int> idBodega { get; set; }
        public Nullable<int> valor { get; set; }
        public string idTMovimiento { get; set; }
        public string idProveedor { get; set; }
    
        public virtual bodega bodega { get; set; }
        public virtual producto producto { get; set; }
        public virtual proveedor proveedor { get; set; }
        public virtual tipomovimiento tipomovimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<producto_bodega> producto_bodega { get; set; }
    }
}
