//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LujetonA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto_bodega
    {
        public int id { get; set; }
        public Nullable<int> idProducto { get; set; }
        public Nullable<int> idBodega { get; set; }
        public Nullable<int> idMovimiento { get; set; }
        public Nullable<int> cantidad { get; set; }
    
        public virtual bodega bodega { get; set; }
        public virtual movimiento movimiento { get; set; }
        public virtual producto producto { get; set; }
    }
}
