//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LujetonA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_producto_real_stock
    {
        public int id { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> stock_total { get; set; }
        public Nullable<double> precio_unidad { get; set; }
        public string idCategoria { get; set; }
        public string imagen { get; set; }
        public Nullable<double> precio_venta { get; set; }
        public string categoria_nombre { get; set; }
        public string existencia { get; set; }
    }
}
